const characters = [
	{
		playerName: 'Alejandro',
		pronouns: 'They/Them',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-pizza-dude-person',
		characterActualName: 'Chetoslovakie "Chet" Loosey',
		characterName:'The Pizza Dude',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		email: 'chet@protocultura.net',
		timeZone: 'GMT-3',
		bio: 'An average pizza dude who\'s gotten caught up in the affairs of the night.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Andy',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/edgar-d-sault-person',
		characterActualName:'Edgar D. Sault',
		characterName:'The Extractor',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		email: 'DuskCitySault@hotmail.com',
		timeZone: 'BST',
		bio: 'An opportunistic businessman looking to take what he can to build an empire.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'Ben D.',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/remulus-person',
		characterActualName:'Remulus',
		characterName:'The Wild Child',
		tag: 'Factionless',
		controlEmail: 'duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'BST',
		bio: 'A feral child torn between the law of the jungle and the call of humanity.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'Clare',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-dancer-person',
		characterName:'The Dancer',
		tag: 'Brother\'s Wrath',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		email: 'dancer.dusk@gmail.com',
		timeZone: 'BST',
		bio: 'A performer and professional trying to transcend the limits of her ability.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Dan',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-perfectionist-person',
		characterName:'The Perfectionist',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'JST',
		bio: 'An incredibly particular person who desires a truly perfect world.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'Ben K.',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-sheriff-person',
		charracterActualName:'',
		characterName:'The Sheriff',
		tag: 'Brother\'s Wrath',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'EST',
		bio: 'Someone who has turned their back on humanity, in order to protect the world behind the Shroud.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'Dominique',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/etienne-daedalos-person',
		characterActualName:'Etienne Daedalos',
		characterName:'The Builder',
		tag: 'Brother\'s Wrath',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'CEST',
		bio: 'A maker of barriers, and a builder of walls.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'David',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-punk-person',
		characterName:'The Punk',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'EST',
		bio: 'A stone cold renegade looking for a brand new start.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'Emily',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-haunted-person',
		characterName:'The Haunted',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'BST',
		bio: 'A conduit for the worlds of the living, the dead, and those in between.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'Eli',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-survivor-person',
		characterName:'The Survivor',
		tag: 'Brother\'s Wrath',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		email: 'wintercross-megagames@outlook.com.au',
		timeZone: 'GMT+8',
		bio: 'A sign that love conquers almost everything.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Greg',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-pathfinder-person',
		characterActualName:'Sheridan',
		characterName:'The Pathfinder',
		tag: 'Brother\'s Wrath',
		controlEmail: 'duskcontrolcentral@gmail.com stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'sheridan.pathfinder@gmail.com',
		timeZone: 'PST',
		bio: 'An eternal optimist charting the path to the future.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Jerry',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-animator-person',
		characterName:'The Animator',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'Madrid+1',
		bio: 'An artist searching for inspiration in inhumanity.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Jessica',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-occultist-person',
		characterName:'The Occultist',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'CST',
		bio: 'A dabbler in that which man was not meant to know.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Jim',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-seeker-of-knowledge-person',
		characterName:'The Seeker of Knowledge',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'GMT',
		bio: 'A querent of answers who delights in both the journey and the destination.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'John K.',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-programmer-person',
		characterName:'The Programmer',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		email: 'spa263-programmer@yahoo.com',
		timeZone: 'BST',
		bio: 'A coder connected to the world by invisible threads.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'Kieran',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-numerologist-person',
		characterName:'The Numerologist',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		email: 'afterlifekieran@gmail.com',
		timeZone: 'BST',
		bio: 'A mathematician who played the odds and found enlightmenment.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'Lee',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-media-mogul-person',
		characterName:'The Media Mogul',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'BST',
		bio: 'An influencer of the old-school, manipulating public opinion to keep the Awakened a secret.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'Liam',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/doran-person',
		characterActualName:'Doran',
		characterName:'The Wanderer',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.comduskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		email: 'wandererofduskcity@gmail.com',
		timeZone: 'BST',
		bio: 'A lost soul looking for purpose.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'Mason',
		pronouns: 'He/They',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/kirill-lyubov-person',
		characterActualName:'Kirill Lyubov',
		characterName:'The Savior',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'PST',
		bio: 'A visionary who will grant the weary salvation.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Matty',
		pronouns: 'They/Them',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-sympathetic-person',
		characterName:'The Sympathetic',
		tag: 'Brother\'s Wrath',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'GMT+12',
		bio: 'A bleeding heart who has decided to grow a spine.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'Mike',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-urban-legend-person',
		characterName:'The Urban Legend',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'CDT',
		bio: 'A nobody on the path to becoming a nightmare.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'Mickey',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/ruth-hastings-person',
		characterActualName:'Ruth Hastings',
		characterName:'The Social Worker',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		email: 'mickey.megagames@gmail.com',
		timeZone: 'BST',
		bio: 'A believer in and provider of second chances.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Mikolaj',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-surgeon-person',
		characterName:'The Surgeon',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		email: 'mikolajrwiecek+duskcity@gmail.com',
		timeZone: 'CEST',
		bio: 'A doctor forced to practice from the back-alley, still sworn to his oath.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Duck',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/ambrose-trevalyan-person',
		characterActualName:'Ambrose Trevalyan',
		characterName:'The Storyteller',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		email: 'ambrosetrevalyan@gmail.com',
		timeZone: 'BST',
		bio: 'A beloved TV show host, here to school his kin.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'Pamela',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/delilah-gray-person',
		characterActualName:'Delilah Gray',
		characterName:'The Philosopher',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		email: 'pamela.pbem@gmail.com',
		timeZone: 'EST',
		bio: 'An intellectual attempting to reconcile the truth of Awakening with the reality of living.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Patrick',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-hunter-person',
		characterName:'The Hunter',
		tag: 'Brother\'s Wrath',
		controlEmail: 'duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		email: 'stuart.pbem@gmail.com',
		timeZone: 'CST',
		bio: 'A champion searching for ways to prove his dominance.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Serena',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-entrepreneur-person',
		characterName:'The Entrepreneur',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'EST',
		bio: 'A hot-shot, a has-been, and now a harbinger of change.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'Rob',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-guardian-person',
		characterName:'The Guardian',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'BST',
		bio: 'A man fighting in order to keep hold of his happiness.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'Steph',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/zoe-griffin-person',
		characterActualName:'Zoe Griffin',
		characterName:'The Gumshoe',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'EDT',
		bio: 'An investigator on the hunt for the truth, no matter the form it takes.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'Will',
		pronouns: 'They/Them',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-masked-virtuoso-person',
		characterName:'The Masked Virtuoso',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'BST',
		bio: 'A hidden talent ready to return to the stage.',
		username: 'temp',
		control: 'East Control',
		color: 'ccff00'
	}
];

const npcs = [
	{
		playerName: 'North Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/razmus-person',
		characterName:'Razmus',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'The owner, visionary, and self-styled Master of Ceremonies at the underground fighting ring called the Arena of Valiants, but colloquially known as The Pit.',
		username: 'ljtrigirl',
		control: 'North Control'
	},
	{
		playerName: 'North Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/-old-man--alfie-barnes-person',
		characterName:'Alfie Barnes',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'An older homeless man who\'s always flanked by his dogs Rook and Bishop.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'North Control',
		pronouns: 'They/Them',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/alias-person',
		characterName:'Alias',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'A tattoo artists and Awakened who never wears the same face twice.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'North Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/christopher-foster-person',
		characterName:'Christopher Forth',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'A gravedigger relatively happy with his lot in life, with an interest in the space between life and death.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'North Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/dead-gorgeous-person',
		characterName:'Dead Gorgeous',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'A social media savvy Awakened, and the city\'s resident Princess of Posting.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'North Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/sanoh--sunny--prasansapakit-person',
		characterName:'Sanoh "Sunny" Prasansapakit',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'The city\'s most ruthless haggler, and owner of the Pawn Shop.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'North Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/shani-blake-personn',
		characterName:'Shani Blake',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'The owner of In Full Bloom, who has a smile and a flower for everyone.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'North Control',
		pronouns: 'He/Him',
		worldAnvil: '?',
		characterName:'Jean-Luc Leroux',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'A dark and gloomy young man who works at a clothing store.',
		username: 'temp',
		control: 'North Control'
	},

	{
		playerName: 'South Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/aaron-storme-person',
		characterName:'Aaron Storme',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'The lead anchor and public face of Doxley Local News.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'South Control',
		pronouns: 'They/Them',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/dominik-person',
		characterName:'Dominik',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'The bartender at Thirst, better known for their mixology than their conversation.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'South Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/gustave-person',
		characterName:'Gustave',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'The hotelier at the Empress Hotel, and a consummate professional..',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'South Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/helga-adler-person',
		characterName:'Helga Adler',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'The ambitious, driven leader of the Sister\'s Wisdom.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'South Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/jennifer-yuen-person',
		characterName:'Jennifer Yuen',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'The strong-willed owner of Thirst, she has no time for indecision.',
		username: 'Reeve',
		control: 'South Control'
	},
	{
		playerName: 'South Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/letitia-mayhew-person',
		characterName:'Letitia Mayhew',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'A socialite living the good life.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'South Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/orla-kuchler-person',
		characterName:'Orla Kuchler',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'A chef and patissier who makes all of her food with love.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'South Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/roger-broom-person',
		characterName:'Roger Broom',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'A top architect at Calibre Concepts, whose creations dot the city\'s skyline.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Central Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/chelsea-hubbard-person',
		characterName:'Chelsea Hubbard',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'The third generation owner of Hubbard\'s Bespoke and a woman in the know.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Central Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/devin-slater-person',
		characterName:'Devin Slater',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'Manager at the local branch of Gingko\'s Copies, he lives in a state of perpetual exhaustion.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Central Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/duncan-buchanan-person',
		characterName:'Duncan Buchanan',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'A former hedge knight turned CEO of the Guardian Angels bodyguard service.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Central Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/reginald--reggie--royce-person',
		characterName:'Reginald "Reggie" Royce',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'A nice guy with a love of magic who happens to own the Solstice Theatre.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Central Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/steven-davies-person',
		characterName:'Steven Davies',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'A retiree with strong ties to the financial sector, enjoying his twilight years.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Central Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/susan-chandler-person',
		characterName:'Susan Chandler',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'A shrewd investor, turning old money into very new money.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Central Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/timothy-ipswich-person',
		characterName:'Timothy Ipswich',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'One of a number of clerks working at City Hall.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Central Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/bobby-weber-person',
		characterName:'Bobby Weber',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'The manager of the Second Chance Blood Bank and a paranoid conspiracy theorist',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Central Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/dave-busters-person',
		characterName:'Dave Busters',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'EST',
		bio: 'The totally radical owner of Count Radula\'s House of Pizza, dude!',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Dusk City Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/diego-armando-person',
		characterName:'Diego Armando',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'GMT+8',
		bio: 'The Keeper of the Land, who serves as guardian and spiritual leader.',
		username: 'PiFace314',
		control: 'Dusk City Control'
	},
	{
		playerName: 'Dusk City Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/cassandra-E2809CcassE2809D-hasapi-person',
		characterName:'Cassandra Hasapi',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'GMT+8',
		bio: 'A librarian at the Doxley City Library, who keeps records for the Awakened.',
		username: 'temp',
		control: 'Dusk City Control'
	},
	{
		playerName: 'Dusk City Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/father-rex-davidson-person',
		characterName:'Father Rex Davidson',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'GMT+8',
		bio: 'A televangelist and actor who preaches a philosophy of peace, understanding, and the eradication of evil.',
		username: 'temp',
		control: 'Dusk City Control'
	},
	{
		playerName: 'Dusk City Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/mayor-shivani-chowdhury-person',
		characterName:'Mayor Shivani Chowdhury',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'GMT+8',
		bio: 'The recently elected Mayor of Doxley, Mayor Shivani is a woman with a vision and a lot to prove',
		username: 'temp',
		control: 'Dusk City Control'
	},
	{
		playerName: 'Dusk City Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/maxine-hawthorne-person',
		characterName:'Maxine Hawthorne',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'GMT+8',
		bio: 'Advance Inc’s direct representative in Doxley City, and the Director for North-Eastern Expansion in Great Britain and its Territories.',
		username: 'temp',
		control: 'Dusk City Control'
	},
	{
		playerName: 'South Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/maisie-walliams-person',
		characterName:'Maisie Walliams',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'The cheerful owner of the White Hart.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'West Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/alan-monty-person',
		characterName:'Alan Monty',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'UTC+3',
		bio: 'A scatterbrained professor and researcher at Doxley University.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'West Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/greg-toska-person',
		characterName:'Greg Toska',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'UTC+3',
		bio: 'A city councilor and first among Unifier equals.',
		username: 'Murska',
		control: 'West Control'
	},
	{
		playerName: 'West Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/james--bigs--marras-person',
		characterName:'James "Bigs" Marras',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'UTC+3',
		bio: 'The owner of Marras Construction, the local choice of contractor.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'West Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/charles-layton-person',
		characterName:'Charles Layton',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'UTC+3',
		bio: 'A powerful and wealthy member of the Sister\'s Wisdom, who lives in an apartment block he calls his personal fiefdom.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'West Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/lucia-siska-person',
		characterName:'Lucia Siska',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'UTC+3',
		bio: 'The new and ambitious head of Jensen Transport\'s local branch.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'West Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/marivic--mari--belen-person',
		characterName:'Marivic "Mari" Belen',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'UTC+3',
		bio: 'A third year Communications student at the University of Doxley, and the President of the Broadcast Society.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'West Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/ray-johnson-person',
		characterName:'Ray Johnson',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'UTC+3',
		bio: 'The owner of City Slicker Records, and a man of few words.',
		username: 'temp',
		control: 'Zeta Control'
	},
	{
		playerName: 'Dusk City Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/dj-pyro-person',
		characterName:'DJ Pyro',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'GMT+8',
		bio: 'The city\'s #1 Awakened radio personality, and host of the Witching Hour.',
		username: 'temp',
		control: 'Dusk City Control'
	},
	{
		playerName: 'West Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/adrian-montgomery-person',
		characterName:'Adrian Montgomery',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'UTC+3',
		bio: 'A respected figure in the Sister\'s Wisdom who acts as their Enforcer.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'West Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/michael--mike--tharson-person',
		characterName:'Michael "Mike" Tharson',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'UTC+3',
		bio: 'Enforcer for the Brother\'s Wrath, and a believer in the applied violence school of problem solving.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'West Control',
		pronouns: 'She/her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/alice-palmer-person',
		characterName:'Alice Palmer',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'UTC+3',
		bio: 'Owner of the Garden of Hesperides, the city\'s finest dining establishment.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'East Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/ciara-rowland-person',
		characterName:'Ciara Rowland',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'The singer and proprietress of the Clover Lounge, known for her bittersweet voice.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'East Control',
		pronouns: 'They/Them',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/j-doe-person',
		characterName:'J Doe',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'An enigma whose presence is known only through an irregular supply of notes.',
		username: 'Game Control',
		control: 'East Control'
	},
	{
		playerName: 'East Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/oda-orochi-person',
		characterName:'Oda Orochi',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'A leader and mentor to the members of the Brother\'s Wrath, and a strict adherent to the Laws of the Awakened.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'East Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/peter-black-person',
		characterName:'Peter Black',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'A forensic pathologist, coroner, and occasional falsifyer of deaths.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'East Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/reynard-fennick-person',
		characterName:'Reynard Fennick',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'The city\'s resident trickster, though cruder words may be more apt.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'East Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/samhain-walsh-person',
		characterName:'Samhain Walsh',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'A Predator who has found herself well adapted to the modern age.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'East Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/jeong-gwon--johnny--baek-person',
		characterName:'Jeong-Gwon "Johnny" Baek',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'BST',
		bio: 'A bent cop, though not completely crooked.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'Dusk City Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/melanie-yeoh-person',
		characterName:'Melanie Yeoh',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'GMT+8',
		bio: 'A reporter and meteorologist looking for the next big scoop.',
		username: 'temp',
		control: 'Dusk City Control'
	},
	{
		playerName: 'Dusk City Control',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/josephine-rosales-person',
		characterName:'Josephine Rosales',
		tag: 'NPC',
		controlEmail: '',
		email: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'GMT+8',
		bio: 'An emergency room nurse with a professional attitude and a little homesickness.',
		username: 'temp',
		control: 'Dusk City Control'
	},
	{
		playerName: 'Scott',
		pronouns: 'They/Them',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/leone-harris-person',
		characterName:'Leone Harris',
		tag: 'NPC',
		email: 'scott.megagames@gmail.com',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'PT',
		bio: 'A fence who can get you what you want, when you want it... if you can pay.',
		username: 'BobtheNinjaMan',
		control: 'Scott'
	}
];

module.exports = { characters, npcs };