const characters = [
	{
		playerName: 'Alejandro',
		pronouns: 'They/Them',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-pizza-dude-person',
		characterActualName: 'Chetoslovakie "Chet" Loosey',
		characterName:'The Pizza Dude',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		email: 'chet@protocultura.net',
		timeZone: 'GMT-3',
		bio: 'An average pizza dude who\'s gotten caught up in the affairs of the night.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Andy',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/edgar-d-sault-person',
		characterActualName:'Edgar D. Sault',
		characterName:'The Extractor',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		email: 'DuskCitySault@hotmail.com',
		timeZone: 'BST',
		bio: 'An opportunistic businessman looking to take what he can to build an empire.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'Ben D.',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/remulus-person',
		characterActualName:'Remulus',
		characterName:'The Wild Child',
		tag: 'Factionless',
		controlEmail: 'duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'BST',
		bio: 'A feral child torn between the law of the jungle and the call of humanity.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'Clare',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-dancer-person',
		characterName:'The Dancer',
		tag: 'Brother\'s Wrath',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		email: 'dancer.dusk@gmail.com',
		timeZone: 'BST',
		bio: 'A performer and professional trying to transcend the limits of her ability.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Dan',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-perfectionist-person',
		characterName:'The Perfectionist',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'JST',
		bio: 'An incredibly particular person who desires a truly perfect world.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'Ben K.',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-sheriff-person',
		charracterActualName:'',
		characterName:'The Sheriff',
		tag: 'Brother\'s Wrath',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'EST',
		bio: 'Someone who has turned their back on humanity, in order to protect the world behind the Shroud.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'Dominique',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/etienne-daedalos-person',
		characterActualName:'Etienne Daedalos',
		characterName:'The Builder',
		tag: 'Brother\'s Wrath',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'CEST',
		bio: 'A maker of barriers, and a builder of walls.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'David',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-punk-person',
		characterName:'The Punk',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com; duskcontrolnorth@gmail.com; duskcitycontrol@gmail.com;',
		email: 'no email yet',
		timeZone: 'EST',
		bio: 'A stone cold renegade looking for a brand new start.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'Emily',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-haunted-person',
		characterName:'The Haunted',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'BST',
		bio: 'A conduit for the worlds of the living, the dead, and those in between.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'Eli',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-survivor-person',
		characterName:'The Survivor',
		tag: 'Brother\'s Wrath',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		email: 'wintercross-megagames@outlook.com.au',
		timeZone: 'GMT+8',
		bio: 'A sign that love conquers almost everything.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Greg',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-pathfinder-person',
		characterActualName:'Sheridan',
		characterName:'The Pathfinder',
		tag: 'Brother\'s Wrath',
		controlEmail: 'duskcontrolcentral@gmail.com stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'sheridan.pathfinder@gmail.com',
		timeZone: 'PST',
		bio: 'An eternal optimist charting the path to the future.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Jerry',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-animator-person',
		characterName:'The Animator',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'Madrid+1',
		bio: 'An artist searching for inspiration in inhumanity.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Jessica',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-occultist-person',
		characterName:'The Occultist',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'CST',
		bio: 'A dabbler in that which man was not meant to know.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Jim',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-seeker-of-knowledge-person',
		characterName:'The Seeker of Knowledge',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'GMT',
		bio: 'A querent of answers who delights in both the journey and the destination.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'John K.',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-programmer-person',
		characterName:'The Programmer',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		email: 'spa263-programmer@yahoo.com',
		timeZone: 'BST',
		bio: 'A coder connected to the world by invisible threads.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'Kieran',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-numerologist-person',
		characterName:'The Numerologist',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		email: 'afterlifekieran@gmail.com',
		timeZone: 'BST',
		bio: 'A mathematician who played the odds and found enlightmenment.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'Lee',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-media-mogul-person',
		characterName:'The Media Mogul',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'BST',
		bio: 'An influencer of the old-school, manipulating public opinion to keep the Awakened a secret.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'Liam',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/doran-person',
		characterActualName:'Doran',
		characterName:'The Wanderer',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.comduskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		email: 'wandererofduskcity@gmail.com',
		timeZone: 'BST',
		bio: 'A lost soul looking for purpose.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'Mason',
		pronouns: 'He/They',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/kirill-lyubov-person',
		characterActualName:'Kirill Lyubov',
		characterName:'The Savior',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'PST',
		bio: 'A visionary who will grant the weary salvation.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Matty',
		pronouns: 'They/Them',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-sympathetic-person',
		characterName:'The Sympathetic',
		tag: 'Brother\'s Wrath',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'GMT+12',
		bio: 'A bleeding heart who has decided to grow a spine.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'Mike',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-urban-legend-person',
		characterName:'The Urban Legend',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'CDT',
		bio: 'A nobody on the path to becoming a nightmare.',
		username: 'temp',
		control: 'East Control'
	},
	{
		playerName: 'Mickey',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/ruth-hastings-person',
		characterActualName:'Ruth Hastings',
		characterName:'The Social Worker',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		email: 'mickey.megagames@gmail.com',
		timeZone: 'BST',
		bio: 'A believer in and provider of second chances.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Mikolaj',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-surgeon-person',
		characterName:'The Surgeon',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		email: 'mikolajrwiecek+duskcity@gmail.com',
		timeZone: 'CEST',
		bio: 'A doctor forced to practice from the back-alley, still sworn to his oath.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Duck',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/ambrose-trevalyan-person',
		characterActualName:'Ambrose Trevalyan',
		characterName:'The Storyteller',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		email: 'ambrosetrevalyan@gmail.com',
		timeZone: 'BST',
		bio: 'A beloved TV show host, here to school his kin.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'Pamela',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/delilah-gray-person',
		characterActualName:'Delilah Gray',
		characterName:'The Philosopher',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolsouth@gmail.com duskcitycontrol@gmail.com',
		email: 'pamela.pbem@gmail.com',
		timeZone: 'EST',
		bio: 'An intellectual attempting to reconcile the truth of Awakening with the reality of living.',
		username: 'temp',
		control: 'South Control'
	},
	{
		playerName: 'Patrick',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-hunter-person',
		characterName:'The Hunter',
		tag: 'Brother\'s Wrath',
		controlEmail: 'duskcontrolcentral@gmail.com duskcitycontrol@gmail.com',
		email: 'stuart.pbem@gmail.com',
		timeZone: 'CST',
		bio: 'A champion searching for ways to prove his dominance.',
		username: 'temp',
		control: 'Central Control'
	},
	{
		playerName: 'Serena',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-entrepreneur-person',
		characterName:'The Entrepreneur',
		tag: 'Sister\'s Wisdom',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolnorth@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'EST',
		bio: 'A hot-shot, a has-been, and now a harbinger of change.',
		username: 'temp',
		control: 'North Control'
	},
	{
		playerName: 'Rob',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-guardian-person',
		characterName:'The Guardian',
		tag: 'Unifiers',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'BST',
		bio: 'A man fighting in order to keep hold of his happiness.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'Steph',
		pronouns: 'She/Her',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/zoe-griffin-person',
		characterActualName:'Zoe Griffin',
		characterName:'The Gumshoe',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcontrolwest@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'EDT',
		bio: 'An investigator on the hunt for the truth, no matter the form it takes.',
		username: 'temp',
		control: 'West Control'
	},
	{
		playerName: 'Will',
		pronouns: 'They/Them',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/the-masked-virtuoso-person',
		characterName:'The Masked Virtuoso',
		tag: 'Factionless',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		email: 'no email yet',
		timeZone: 'BST',
		bio: 'A hidden talent ready to return to the stage.',
		username: 'temp',
		control: 'East Control',
		color: 'ccff00'
	}
];

const npcs = [
	{
		playerName: 'North Control',
		pronouns: 'He/Him',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/razmus-person',
		characterName:'Razmus',
		tag: 'NPC',
		controlEmail: 'stuart.pbem@gmail.com  duskcitycontrol@gmail.com',
		email: 'duskcontrolnorth@gmail.com',
		timeZone: 'EST',
		bio: 'The owner, visionary, and self-styled Master of Ceremonies at the underground fighting ring called the Arena of Valiants, but colloquially known as The Pit.',
		username: 'ljtrigirl',
		control: 'North Control'
	},
	{
		playerName: 'Scott',
		pronouns: 'They/Them',
		worldAnvil: 'https://www.worldanvil.com/w/dusk-city-by-night-afterlife-control/a/leone-harris-person',
		characterName:'Leone Harris',
		tag: 'NPC',
		email: 'scott.megagames@gmail.com',
		controlEmail: 'stuart.pbem@gmail.com duskcitycontrol@gmail.com',
		timeZone: 'PT',
		bio: 'A fence who can get you what you want, when you want it... if you can pay.',
		username: 'BobtheNinjaMan',
		control: 'Scott'
	}
];

module.exports = { characters, npcs };